language: php

php:
  - 5.6
  - 7.1

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer create-project
# setup application:
  - |
    ./init --env=Development

before_script:
  - mysql -e 'CREATE DATABASE yii2mod_base_test;'
  - cd tests/bin && php yii migrate --interactive=0 && php yii rbac/migrate --interactive=0 && cd ../..

script:
  - vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --dry-run --diff
  - bin/codecept run
